REM-1208: Integrate our BatchInjector
Remmeauth/sawtooth-core pull request #2
Opened 2019-03-18 13:07 UTC by Art17

### Jira references
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-1208

2019-03-23 20:22 UTC, eugene-babichenko requested changes
1. Transactions/batches should always have some random `nonce`, not the default value. This is the requirement, because, transaction bodies will often be the same, signed by the same signers and thus have same ids. Using nonces will resolve that.
2. Not really sure should our batch be injected in the beginning or in the end of the block.
3. Our injector should also reuse batch injector for `BlockInfo` so that we have a single batch injector to control all injections being done.

2019-03-23 20:22 UTC, eugene-babichenko commented on validator/sawtooth_validator/journal/batch_injector.py
> +            block_info_injector = importlib.import_module(
The wrong object is created here, not our own injector.

2019-03-23 20:22 UTC, eugene-babichenko commented on validator/sawtooth_validator/journal/obligatory_payment_injector.py
> +        INPUTS = OUTPUTS = [
Addressing is entirely wrong, should be fixed.

2019-03-23 20:22 UTC, eugene-babichenko commented on validator/sawtooth_validator/journal/obligatory_payment_injector.py
> +            payload_sha512=hash512(payload).hexdigest(),
This causes an error.

2019-03-27 09:33 UTC, DeV1doR commented on validator/sawtooth_validator/journal/remme_batch_injector.py
> +            payload=payload,
Why payload here as `ObligatoryPaymentPayload` proto, if it required to be `TransactionPayload` for correct transaction processing?

2019-03-29 13:54 UTC, merged